title: Bram Verstappen
description: Creative developer and builder
author: Bram Verstappen
email: bram.verstappen@student.uhasselt.be
url: "https://bramverstappen.github.io"
show_downloads: false
include:
  - .nojekyll